USE hotel_management;

-- ==========================================================
-- Query 1
-- Question:
-- Display all booking information, including booking ID,
-- guest full name, check-in date, check-out date and status.
--
-- SQL Concepts:
-- SELECT, JOIN
-- ==========================================================
SELECT
    b.booking_id,
    CONCAT(g.first_name, ' ', g.last_name) AS guest_name,
    b.check_in_date,
    b.check_out_date,
    b.booking_status
FROM Booking b
JOIN Guest g ON b.guest_id = g.guest_id
ORDER BY b.booking_id;

-- ==========================================================
-- Query 2
-- Question:
-- Display all rooms with their room type, price per night
-- and current room status.
--
-- SQL Concepts:
-- JOIN, ORDER BY
-- ==========================================================
SELECT
    r.room_number,
    rt.type_name,
    rt.price_per_night,
    r.status
FROM Room r
JOIN RoomType rt ON r.room_type_id = rt.room_type_id
ORDER BY r.room_number;

-- ==========================================================
-- Query 3
-- Question:
-- Calculate the total revenue generated by each room type.
--
-- SQL Concepts:
-- JOIN, GROUP BY, SUM
-- ==========================================================
SELECT
    rt.type_name,
    SUM(p.amount) AS total_revenue
FROM Payment p
JOIN Booking b ON p.booking_id = b.booking_id
JOIN BookingRoom br ON b.booking_id = br.booking_id
JOIN Room r ON br.room_id = r.room_id
JOIN RoomType rt ON r.room_type_id = rt.room_type_id
WHERE p.payment_status = 'Paid'
GROUP BY rt.type_name
ORDER BY total_revenue DESC;

-- ==========================================================
-- Query 4
-- Question:
-- Find guests whose total spending exceeds £500.
--
-- SQL Concepts:
-- JOIN, GROUP BY, HAVING
-- ==========================================================
SELECT
    CONCAT(g.first_name, ' ', g.last_name) AS guest_name,
    SUM(p.amount) AS total_spent
FROM Guest g
JOIN Booking b ON g.guest_id = b.guest_id
JOIN Payment p ON b.booking_id = p.booking_id
WHERE p.payment_status = 'Paid'
GROUP BY guest_name
HAVING SUM(p.amount) > 500
ORDER BY total_spent DESC;

-- ==========================================================
-- Query 5
-- Question:
-- Classify guests into customer levels based on their total
-- spending.
--
-- SQL Concepts:
-- CASE WHEN, GROUP BY
-- ==========================================================
SELECT
    CONCAT(g.first_name, ' ', g.last_name) AS guest_name,
    SUM(p.amount) AS total_spent,
    CASE
        WHEN SUM(p.amount) >= 1500 THEN 'VIP'
        WHEN SUM(p.amount) >= 800 THEN 'Regular'
        ELSE 'Basic'
    END AS customer_level
FROM Guest g
JOIN Booking b ON g.guest_id = b.guest_id
JOIN Payment p ON b.booking_id = p.booking_id
WHERE p.payment_status = 'Paid'
GROUP BY guest_name
ORDER BY total_spent DESC;

-- ==========================================================
-- Query 6
-- Question:
-- Find the room with the highest booking frequency.
--
-- SQL Concepts:
-- Subquery, GROUP BY, ORDER BY
-- ==========================================================
SELECT
    r.room_id,
    r.room_number,
    rt.type_name,
    COUNT(br.booking_id) AS booking_count
FROM Room r
JOIN RoomType rt ON r.room_type_id = rt.room_type_id
JOIN BookingRoom br ON r.room_id = br.room_id
WHERE r.room_id =
(
    SELECT room_id
    FROM BookingRoom
    GROUP BY room_id
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
GROUP BY r.room_id, r.room_number, rt.type_name;

-- ==========================================================
-- Query 7
-- Question:
-- Display guests whose total spending is higher than the
-- average guest spending.
--
-- SQL Concepts:
-- CTE, Aggregate Function, Subquery
-- ==========================================================
WITH GuestSpending AS
(
    SELECT
        g.guest_id,
        CONCAT(g.first_name, ' ', g.last_name) AS guest_name,
        SUM(p.amount) AS total_spent
    FROM Guest g
    JOIN Booking b ON g.guest_id = b.guest_id
    JOIN Payment p ON b.booking_id = p.booking_id
    WHERE p.payment_status = 'Paid'
    GROUP BY g.guest_id, guest_name
)
SELECT
    guest_id,
    guest_name,
    total_spent
FROM GuestSpending
WHERE total_spent >
(
    SELECT AVG(total_spent)
    FROM GuestSpending
)
ORDER BY total_spent DESC;

-- ==========================================================
-- Query 8
-- Question:
-- Rank guests based on their total spending.
--
-- SQL Concepts:
-- Window Function, RANK
-- ==========================================================
SELECT
    CONCAT(g.first_name, ' ', g.last_name) AS guest_name,
    SUM(p.amount) AS total_spent,
    RANK() OVER (ORDER BY SUM(p.amount) DESC) AS spending_rank
FROM Guest g
JOIN Booking b ON g.guest_id = b.guest_id
JOIN Payment p ON b.booking_id = p.booking_id
WHERE p.payment_status = 'Paid'
GROUP BY guest_name
ORDER BY spending_rank;

-- ==========================================================
-- Query 9
-- Question:
-- Calculate the average customer rating for each room type.
--
-- SQL Concepts:
-- JOIN, GROUP BY, AVG
-- ==========================================================
SELECT
    rt.type_name,
    ROUND(AVG(rv.rating), 2) AS average_rating,
    COUNT(rv.review_id) AS review_count
FROM Review rv
JOIN Booking b ON rv.booking_id = b.booking_id
JOIN BookingRoom br ON b.booking_id = br.booking_id
JOIN Room r ON br.room_id = r.room_id
JOIN RoomType rt ON r.room_type_id = rt.room_type_id
GROUP BY rt.type_name
ORDER BY average_rating DESC;

-- ==========================================================
-- Query 10
-- Question:
-- Create a view to display guest booking and payment information.
--
-- SQL Concepts:
-- VIEW, JOIN
-- ==========================================================
CREATE OR REPLACE VIEW GuestBookingSummary AS
SELECT
    CONCAT(g.first_name, ' ', g.last_name) AS guest_name,
    b.booking_id,
    b.check_in_date,
    b.check_out_date,
    p.amount,
    p.payment_status
FROM Guest g
JOIN Booking b ON g.guest_id = b.guest_id
JOIN Payment p ON b.booking_id = p.booking_id;

SELECT *
FROM GuestBookingSummary
ORDER BY booking_id;
